# Generated by Django 3.1.7 on 2021-03-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Müdür'), (2, 'Öğretmen'), (3, 'Öğrenci')], default=3, verbose_name='Kullanıcı Tipi'),
        ),
    ]
