# Generated by Django 3.1.7 on 2021-03-27 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('user', '0003_auto_20210327_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sinif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='classes.sinif'),
        ),
    ]
