# Generated by Django 3.1.7 on 2021-03-28 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
        ('user', '0004_account_sinif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sinif',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='classes.sinif'),
        ),
    ]
